dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8

script:
  - mkdir out && cd out
  - CXX=/usr/bin/g++-8 CC=/usr/bin/gcc-8 cmake ..
  - cmake --build .
  - ./poker-tests

notifications:
  email:
    false
