version: 1.0.{build}
image: Visual Studio 2017
build_script:
- cmd: >-
    git submodule update --init

    mkdir out

    cd out

    cmake .. -G"Visual Studio 15 2017 Win64"

    cmake --build . -- /nologo /verbosity:quiet
test_script:
- cmd: >-
    dir

    cd Debug

    poker-tests.exe